#!/usr/bin/env python
from __future__ import division

import argparse
parser = argparse.ArgumentParser()
parser.add_argument('path',help='path to images')
args = parser.parse_args()

import os
import sys
import numpy as np
import cv2

imL = cv2.imread('%s/sphericalL.png'%args.path)
imR = cv2.imread('%s/sphericalR.png'%args.path)
imout = np.stack([imR[:,:,0],imR[:,:,1],imL[:,:,2]],axis=-1)
cv2.imwrite('%s/anaglyph.png'%args.path,imout)
